{TEXT("序章 · 失联：你是进入设施排查失联事件的应急队员，接受暴露检查后在九号留观区醒来。地面出口被封锁，眼下的目标是建立联系、寻找离开的路。"),TEXT("PROLOGUE: You entered the facility to investigate missing personnel. After an exposure check, you wake in Ward Nine. Surface exits are sealed. Establish contact and find a way out.")},
{TEXT("林岑：终于有人回应了。我是设施工程师。你还在九号留观区，外门已被封锁。备用门禁卡放在医疗推车旁。清除走廊里的威胁，取回卡后到尽头气闸来。"),TEXT("Lin Cen: I'm the facility engineer. Ward Nine's outer doors are sealed. Clear the corridor, collect the spare card by the trolley, and reach the airlock.")},
{TEXT("转运记录：患者 00 被送往地下培养站。林岑：地面出口仍被封锁，地下运输线通向设施另一侧。恢复地铁供电，沿转运路线寻找出口和失联人员。"),TEXT("TRANSFER LOG: Patient 00 went underground. Lin Cen: surface exits are sealed, but the subway crosses the facility. Restore power and follow it to find survivors and an exit.")},
{TEXT("值班记录：转运对象 00，目的地为地下培养站。林岑：先别追查，拿护士卡开启气闸。它只能带你离开留观区，主病区仍需恢复供电。"),TEXT("Duty log: Subject 00 was sent to the underground growth station. Lin Cen: use the nurse's card at the airlock. The main ward still needs power.")},
{TEXT("WASD 移动  E 交互  1–5 切换  R 装填  G 手雷  M 小地图  H 血条  J 记录  Esc 菜单"),TEXT("WASD Move   E Use   1–5 Weapons   R Reload   G Grenade   M Map   H Health bars   J Journal   Esc Menu")},
{TEXT("林岑：气闸已解除，沿转运通道进入隔离病区。恢复分区门禁供电，再读取转运员记录；我们得查明地下线路为什么还在运送患者。"),TEXT("Lin Cen: airlock released. Follow the transfer corridor into the ward. Restore door power and read the transfer log. Why are patients still being moved underground?")},
{TEXT("鼠标点击 / 拖动    ↑ ↓ 或 Tab 选择    ← → 调节    Enter 确认    Esc 返回"),TEXT("Click / Drag    Up / Down / Tab: Select    Left / Right: Adjust    Enter: Confirm    Esc: Back")},
{TEXT("你在留观病床旁醒来，隔离服的空气循环仍在工作。应急广播只剩杂音。先到右侧护士站恢复通讯，弄清这里发生了什么。"),TEXT("You wake beside an observation bed. Your suit still supplies air; the emergency broadcast is only static. Restore comms at the nurses' station on your right.")},
{TEXT("研究记录：零号是原设施安保负责人，现被作为母体维持。林岑：反应堆供应培养热源，先去军械库解除压力联锁。"),TEXT("RESEARCH: Zero was the security chief, now kept alive as a host. Lin Cen: the reactor heats the growth tanks. Release the armory pressure interlocks first.")},
{TEXT("门禁供电恢复。林岑：护士卡已完成身份核验，地下线路还需要转运员授权。读取转运记录，找到通往地铁的入口。"),TEXT("Door power restored. Lin Cen: the nurse's card is verified. Read the transfer log for the second authorization and the subway entrance.")},
{TEXT("↑ 较早记录    ↓ 较新记录       %d / %d 页       J 或 Esc 继续"),TEXT("Up: Earlier    Down: Later       Page %d / %d       J / Esc: Resume")},
{TEXT("www.scottbuckley.com.au · 曲目与改编见 BGM-CREDITS.txt"),TEXT("www.scottbuckley.com.au · Details: BGM-CREDITS.txt")},
{TEXT("转运记录：患者 00 没有撤离，被送往地下培养站。林岑：先恢复地铁供电，我们才能追到运输终点。"),TEXT("TRANSFER LOG: Patient 00 was sent to the growth station, not evacuated. Lin Cen: restore subway power to follow the transport route.")},
{TEXT("林岑：这里是设施工程台。你的隔离服还能撑住，先找回病区的两张门禁卡，我会引导你离开地下设施。"),TEXT("Lin Cen: facility engineering here. Your suit is holding. Recover both ward keycards; I'll guide you out.")},
{TEXT("安全联锁解除。林岑：现在可以进入反应堆，过载必须按冷却、培养循环、主核心的顺序执行。"),TEXT("Interlock released. Lin Cen: overload cooling, cut the growth cycle, then shut down the core. Follow that order.")},
{TEXT("地下运输线路启动。林岑：温室仍在供养感染源，我们需要密封样本才能确定怎么终止它。"),TEXT("The transport line is running. Lin Cen: the greenhouse still feeds the infection. Seal samples so we can work out how to stop it.")},
{TEXT("样本 A：感染组织仍在摄取营养。这里不是废弃温室，而是一座正在工作的培养设施。"),TEXT("SAMPLE A: infected tissue still absorbs nutrients. This greenhouse is an active growth facility.")},
{TEXT("林岑：收到样本和记录。隔离协议结束——我们会让外面的人知道这里发生了什么。"),TEXT("Lin Cen: samples and records received. Quarantine protocol is over. The outside world will learn what happened here.")},
{TEXT("培养循环切断。典狱长失去抑制，注意地面的重砸预警；它会在重伤后再次暴走。"),TEXT("Growth cycle cut. The Warden is free. Avoid its marked slam zones; severe wounds will trigger another rage.")},
{TEXT("1–5 / 滚轮换武器 · R 装填 · G 手雷 · Q 治疗"),TEXT("1–5 / Wheel: Weapons · R: Reload · G: Grenade · Q: Heal")},
{TEXT("M 显示/隐藏小地图 · H 显示/隐藏血条 · J 查看记录。"),TEXT("M: Minimap · H: Health bars · J: Field journal")},
{TEXT("林岑：感染源已经切断。带着样本去撤离门，我们要把这份记录送出去。"),TEXT("Lin Cen: the infection source is cut off. Take the samples to extraction. Get this evidence out.")},
{TEXT("主供压管线已释放。广播：紧急协议被零号权限覆盖，安保隔离解除。"),TEXT("Main pressure released. Broadcast: Subject Zero has overridden emergency protocol. Security containment is offline.")},
{TEXT("林岑：这是护士长的卡。地下通道需要双人授权，找到负责转运的人。"),TEXT("Lin Cen: that's the head nurse's card. The tunnel needs a second authorization. Find the transfer officer.")},
{TEXT("应急线路已恢复。站台的腐蚀痕迹通向信号柜，留意远处的喷吐声。"),TEXT("Emergency power restored. Corrosion leads toward the signal cabinet. Listen for distant spitters.")},
{TEXT("序章 → 病区 → 地铁 → 温室 → 军械库 → 反应堆"),TEXT("Prologue > Ward > Subway > Greenhouse > Armory > Reactor")},
{TEXT("样本 B：活性在断电后仍持续上升。强行关闭可能使载体暴走。"),TEXT("SAMPLE B: activity keeps rising after power loss. A forced shutdown could send the host into a rage.")},
{TEXT("行动记录：回收感染样本，终止零号培养，并从地下设施撤离。"),TEXT("MISSION: recover infection samples, terminate Subject Zero's growth cycle, and escape the underground facility.")},
{TEXT("拖动滑条或点击 − / +，每次微调 0.05 倍。"),TEXT("Drag the slider or use − / + for 0.05x steps.")},
{TEXT("支路压力下降。重卫仍在执行封锁命令，从侧面绕过盾牌。"),TEXT("Branch pressure is falling. The heavy guard still holds the blockade. Flank its shield.")},
{TEXT("M 小地图开关 · H 怪物血条开关（自动保存）。"),TEXT("M: Minimap · H: Enemy health bars (saved automatically)")},
{TEXT("信号日志：末班运送的不是乘客，是温室的活体培养舱。"),TEXT("Signal log: the last train carried live growth tanks from the greenhouse, not passengers.")},
{TEXT("声音设置可关闭剧情语音，字幕与 J 行动记录保留。"),TEXT("Disable story voices in Audio. Subtitles and journal stay available.")},
{TEXT("生命 %03d    手雷 %d    医疗 %d"),TEXT("HP %03d    Grenades %d    Medkits %d")},
{TEXT("跟随左上角的目标，清除威胁，靠近设备按 E 操作。"),TEXT("Follow the objective. Clear threats, then press E at the device.")},
{TEXT("随时按 Esc 暂停，调整设置或查看完整操作说明。"),TEXT("Press Esc to pause, change settings or view controls.")},
{TEXT("离线试玩 · 设置自动保存 · 战役进度暂不存档"),TEXT("Offline demo · Settings saved · No campaign saves")},
{TEXT("WASD 移动 · 鼠标左键攻击 · 右键瞄准"),TEXT("WASD: Move · Left click: Attack · Right click: Aim")},
{TEXT("剧情语音（主角 / 对讲机）：关 · 保留字幕"),TEXT("Story voices: OFF · Subtitles remain on")},
{TEXT("冷却过载启动。核心温度上升，零号已察觉我们。"),TEXT("Cooling overload started. Core temperature is rising. Zero knows we are here.")},
{TEXT("当前战役进度不会保存，操作与声音设置会保留。"),TEXT("Campaign progress will be lost. Your settings will be kept.")},
{TEXT("窗口模式可拖动边框缩放，也可最小化与最大化。"),TEXT("Windowed mode supports resizing, minimize and maximize.")},
{TEXT("林岑：我叫林岑，设施工程师。推车旁有门禁卡。"),TEXT("Lin Cen: Lin Cen, facility engineer. There's a keycard by the trolley.")},
{TEXT("序章 · 九号留观病区：取回值班护士门禁卡"),TEXT("PROLOGUE: Recover the nurse's keycard")},
{TEXT("应用后须在 15 秒内确认，否则自动恢复。"),TEXT("Confirm within 15 seconds or the change reverts.")},
{TEXT("这处设备尚未获得前序授权，先完成当前任务。"),TEXT("Authorization required. Complete the current objective first.")},
{TEXT("降低数值可更精细瞄准；提高数值可更快转身。"),TEXT("Lower for precise aim. Raise for quicker turns.")},
{TEXT("回收多口径弹药 · 四种枪械备用弹药补充"),TEXT("Ammo recovered · All four firearms resupplied")},
{TEXT("这里已经处理完毕。按 J 查看行动记录。"),TEXT("Already completed. Press J to review the journal.")},
{TEXT("林岑：听得见。先拿护士卡，我帮你找出口。"),TEXT("Lin Cen: I hear you. Get the nurse's card. I'll guide you out.")},
{TEXT("主角：安保负责人……他们把人当成了母体。"),TEXT("Responder: The security chief... They turned a person into a host.")},
{TEXT("林岑：最后一道联锁。解开它，才能进核心。"),TEXT("Lin Cen: One last interlock. Release it to reach the core.")},
{TEXT("序章 · 九号留观病区：恢复护士站通讯"),TEXT("PROLOGUE: Restore nurses' station comms")},
{TEXT("林岑：地铁通向另一侧。先接通站台电源。"),TEXT("Lin Cen: The subway leads through. Restore platform power.")},
{TEXT("林岑：不是撤离。接通运输电源，去温室。"),TEXT("Lin Cen: Not an evacuation. Start the transport line. Head for the greenhouse.")},
{TEXT("林岑：带上样本，去撤离门。我给你开锁。"),TEXT("Lin Cen: Take the samples to extraction. I'll unlock the door.")},
{TEXT("WARD 09  /  五区生存试玩"),TEXT("WARD 09 / SURVIVAL DEMO")},
{TEXT("序章 · 九号留观病区：开启转运气闸"),TEXT("PROLOGUE: Open the transfer airlock")},
{TEXT("附近仍有感染者，先确保操作区域安全。"),TEXT("Infected nearby. Secure the area before using this device.")},
{TEXT("主角：卡拿到了。上面写着，转运零号。"),TEXT("Responder: Got the card. It says: Patient Zero transferred.")},
{TEXT("林岑：先开走廊尽头的气闸。小心那边。"),TEXT("Lin Cen: Open the airlock at the end of the hall. Stay alert.")},
{TEXT("林岑：隔着容器也别碰。还有一份样本。"),TEXT("Lin Cen: Don't touch it, even through the glass. One more sample.")},
{TEXT("林岑：热源在反应堆。先去军械库泄压。"),TEXT("Lin Cen: The reactor feeds it. Depressurize the armory first.")},
{TEXT("林岑：我听见了。带着证据，离开这里。"),TEXT("Lin Cen: I hear you. Get out with the evidence.")},
{TEXT("%d 秒后自动恢复原来的显示设置。"),TEXT("Previous display settings return in %d seconds.")},
{TEXT("保存失败，本次游玩仍使用当前设置。"),TEXT("Could not save. Settings remain active this session.")},
{TEXT("保存失败，本次游玩仍使用当前音量。"),TEXT("Could not save. Volume remains active this session.")},
{TEXT("如果画面正常，请选择“保留设置”。"),TEXT("If the picture looks correct, choose Keep settings.")},
{TEXT("操作设置已保存，下次启动自动恢复。"),TEXT("Controls saved for your next session.")},
{TEXT("操作附近任务设备 / 查看行动记录"),TEXT("Use nearby device / Field journal")},
{TEXT("装填 / 投掷手雷 / 使用治疗包"),TEXT("Reload / Throw grenade / Heal")},
{TEXT("主角：这里是九号病区。我被困住了。"),TEXT("Responder: This is Ward Nine. I'm trapped.")},
{TEXT("林岑：读转运记录，补上第二份授权。"),TEXT("Lin Cen: Check the transfer log. We need a second authorization.")},
{TEXT("主角：有电了。墙上这些……是什么？"),TEXT("Responder: Power's on. What is that on the walls?")},
{TEXT("林岑：别碰。去信号柜，留意喷吐声。"),TEXT("Lin Cen: Don't touch it. Find the signal cabinet. Listen for spitters.")},
{TEXT("林岑：它不会让路。从盾牌侧面过去。"),TEXT("Lin Cen: It won't move. Get around the shield.")},
{TEXT("林岑：先过载冷却，再切断培养循环。"),TEXT("Lin Cen: Overload the cooling. Then cut the growth cycle.")},
{TEXT("刀、手枪、散弹枪、冲锋枪、重机枪"),TEXT("Knife, pistol, shotgun, SMG, machine gun")},
{TEXT("剧情语音（主角 / 对讲机）：开"),TEXT("Story voices: ON · Responder / Radio")},
{TEXT("反应堆：清除典狱长并确认最终过载"),TEXT("REACTOR: Defeat the Warden and confirm overload")},
{TEXT("进入暴走：拉开距离，观察攻击预警"),TEXT("ENRAGED: Keep your distance. Watch the attack warnings.")},
{TEXT("隔离失败 · 按 F9 重新开始"),TEXT("YOU DIED · Press F9 to restart")},
{TEXT("主角：护士站接通了。有人听见吗？"),TEXT("Responder: Nurses' station online. Can anyone hear me?")},
{TEXT("主角：气闸开了。还有别的活人吗？"),TEXT("Responder: Airlock's open. Anyone else alive?")},
{TEXT("林岑：我也在找。先恢复病区门禁。"),TEXT("Lin Cen: Still looking. Restore the ward's door power first.")},
{TEXT("主角：门禁亮了。地下通道还锁着。"),TEXT("Responder: Doors have power. The tunnel's still locked.")},
{TEXT("林岑：先封住样本，别让孢子扩散。"),TEXT("Lin Cen: Seal the samples. Keep those spores contained.")},
{TEXT("林岑：查零号的记录，别直接断电。"),TEXT("Lin Cen: Check Zero's records. Don't cut the power yet.")},
{TEXT("主角：支路关了。那家伙还在守门。"),TEXT("Responder: Branch valve's shut. That thing's guarding the door.")},
{TEXT("林岑：稳住，切断培养循环。我在。"),TEXT("Lin Cen: Steady. Cut the growth cycle. I'm here.")},
{TEXT("从九号留观区醒来，找到离开的路"),TEXT("Wake in Ward Nine. Find a way out.")},
{TEXT("回收医疗包 +1 · Q 使用"),TEXT("Medkit +1 · Q: Heal")},
{TEXT("暂停菜单 / 从头重新开始战役"),TEXT("Pause menu / Restart campaign")},
{TEXT("林岑 · CH 09 联络频道"),TEXT("LIN CEN · RADIO CH 09")},
{TEXT("主角：线路通了。温室还在运行。"),TEXT("Responder: Line's running. The greenhouse is still active.")},
{TEXT("主角：第二份。活性比刚才更高。"),TEXT("Responder: Second sample. More active than the first.")},
{TEXT(" · E 拾取 / 靠近回收"),TEXT(" · E Pick up")},
{TEXT("回收手雷 +1 · G 投掷"),TEXT("Grenade +1 · G: Throw")},
{TEXT("当前设备  %.1f 米%s"),TEXT("Objective  %.1f m%s")},
{TEXT("隔离病区：读取转运员门禁记录"),TEXT("WARD: Read the transfer authorization")},
{TEXT("主角：九号留观区……有人吗？"),TEXT("Responder: Ward Nine... Anyone there?")},
{TEXT("主角：通讯断了。先找护士站。"),TEXT("Responder: Comms are dead. Find the nurses' station.")},
{TEXT("主角：联锁开了。现在怎么做？"),TEXT("Responder: Interlock's open. What now?")},
{TEXT("主角：冷却过载。有什么醒了。"),TEXT("Responder: Cooling overloaded. Something woke up.")},
{TEXT("林岑：离开脚下的红圈，别停！"),TEXT("Lin Cen: Get out of the red circle! Keep moving!")},
{TEXT("主角：它倒下了。核心也停了。"),TEXT("Responder: It's down. The core stopped.")},
{TEXT("◆ 当前目标   M 隐藏"),TEXT("◆ Objective   M: Hide")},
{TEXT("军械库：解除反应堆安全联锁"),TEXT("ARMORY: Release the reactor interlock")},
{TEXT("前往撤离门，带走样本和证据"),TEXT("EXTRACTION: Take the samples and evidence to the exit")},
{TEXT("无边框模式使用桌面分辨率。"),TEXT("Borderless uses your desktop resolution.")},
{TEXT("隔离病区：恢复分区门禁供电"),TEXT("WARD: Restore door power")},
{TEXT("主角：末班车运的是培养舱？"),TEXT("Responder: The last train carried growth tanks?")},
{TEXT("W A S D / 鼠标"),TEXT("W A S D / Mouse")},
{TEXT("已恢复切换前的显示设置。"),TEXT("Previous display settings restored.")},
{TEXT("撤离完成 · 证据已保存"),TEXT("EXTRACTION COMPLETE · Evidence secured")},
{TEXT("攻击或挥刀 / 枪械瞄准"),TEXT("Fire or slash / Aim firearm")},
{TEXT("枪声 / 怪物 / 动作"),TEXT("Weapons / Creatures / Actions")},
{TEXT("病区：读取转运员门禁记录"),TEXT("WARD: Read the transfer authorization")},
{TEXT("主角：零号被送到地下了。"),TEXT("Responder: They took Zero underground.")},
{TEXT("主角：封好了。它还在动。"),TEXT("Responder: Sealed. It's still moving.")},
{TEXT("主角：门开了。我还活着。"),TEXT("Responder: Door's open. I'm still alive.")},
{TEXT("军械库：释放主供压管线"),TEXT("ARMORY: Release main pressure")},
{TEXT("地铁：启动地下运输电源"),TEXT("SUBWAY: Start the transport line")},
{TEXT("地铁：接通站台应急供电"),TEXT("SUBWAY: Restore platform power")},
{TEXT("温室：取回零号组织记录"),TEXT("GREENHOUSE: Retrieve Subject Zero's records")},
{TEXT("温室：密封培养样本 A"),TEXT("GREENHOUSE: Seal sample A")},
{TEXT("温室：密封培养样本 B"),TEXT("GREENHOUSE: Seal sample B")},
{TEXT("病区：回收护士站门禁卡"),TEXT("WARD: Recover the nurse's keycard")},
{TEXT("1–5 / 鼠标滚轮"),TEXT("1–5 / Mouse wheel")},
{TEXT("军械库：关闭蒸汽支路"),TEXT("ARMORY: Close the steam branch valve")},
{TEXT("剧情配乐 / BGM"),TEXT("Adaptive music / BGM")},
{TEXT("区域扫描 · 北 ↑"),TEXT("AREA SCAN · N ↑")},
{TEXT("反应堆：切断培养循环"),TEXT("REACTOR: Cut the growth cycle")},
{TEXT("反应堆：启动冷却过载"),TEXT("REACTOR: Overload the cooling system")},
{TEXT("地铁：恢复信号控制柜"),TEXT("SUBWAY: Restore the signal cabinet")},
{TEXT("窗口 / 全屏分辨率"),TEXT("Resolution")},
{TEXT("行动记录 · 已暂停"),TEXT("FIELD JOURNAL · PAUSED")},
{TEXT("主角：主压降下来了。"),TEXT("Responder: Main pressure's down.")},
{TEXT("保留新的显示设置？"),TEXT("Keep these display settings?")},
{TEXT("垂直视角反转：关"),TEXT("Invert mouse Y: OFF")},
{TEXT("垂直视角反转：开"),TEXT("Invert mouse Y: ON")},
{TEXT("声音设置已保存。"),TEXT("Audio settings saved.")},
{TEXT("恢复默认操作设置"),TEXT("Reset controls")},
{TEXT("操作设置已保存。"),TEXT("Control settings saved.")},
{TEXT("显示设置已保存。"),TEXT("Display settings saved.")},
{TEXT("主角：它挣脱了！"),TEXT("Responder: It broke free!")},
{TEXT(" · E 操作"),TEXT(" · E Use")},
{TEXT(" · 弧线挥砍"),TEXT(" · Slash")},
{TEXT(" · 补给已满"),TEXT(" · Full")},
{TEXT("E  操作设备"),TEXT("E  Use device")},
{TEXT("主角 · 近场"),TEXT("RESPONDER · LOCAL")},
{TEXT("准备进入封锁区"),TEXT("READY TO ENTER")},
{TEXT("取消，返回菜单"),TEXT("Cancel / Back")},
{TEXT("左键 / 右键"),TEXT("Left / Right click")},
{TEXT("确认退出到桌面"),TEXT("Quit to desktop")},
{TEXT("移动 / 环视"),TEXT("Move / Look around")},
{TEXT("记录 %02d"),TEXT("ENTRY %02d")},
{TEXT("重新开始战役？"),TEXT("Restart the campaign?")},
{TEXT("%.2f 倍"),TEXT("%.2fx")},
{TEXT("09 号载体"),TEXT("Subject 09")},
{TEXT("应用显示设置"),TEXT("Apply display settings")},
{TEXT("恢复默认音量"),TEXT("Reset volumes")},
{TEXT("确认重新开始"),TEXT("Restart campaign")},
{TEXT("  装填中"),TEXT("  RELOADING")},
{TEXT("总静音：关"),TEXT("Master mute: OFF")},
{TEXT("总静音：开"),TEXT("Master mute: ON")},
{TEXT("恢复原设置"),TEXT("Revert settings")},
{TEXT("战术冲锋枪"),TEXT("Tactical SMG")},
{TEXT("战术格斗刀"),TEXT("Combat Knife")},
{TEXT("无边框窗口"),TEXT("Borderless")},
{TEXT("暗影潜行者"),TEXT("Shadow Stalker")},
{TEXT("泵动散弹枪"),TEXT("Pump Shotgun")},
{TEXT("游戏已暂停"),TEXT("PAUSED")},
{TEXT("环境背景声"),TEXT("Environmental ambience")},
{TEXT("画面与窗口"),TEXT("Display")},
{TEXT("腐囊喷吐者"),TEXT("Blight Spitter")},
{TEXT("裂脊追踪者"),TEXT("Spinebreaker")},
{TEXT("退出游戏？"),TEXT("Quit the game?")},
{TEXT("零号典狱长"),TEXT("Subject Zero: The Warden")},
{TEXT("鼠标与操作"),TEXT("Mouse & controls")},
{TEXT("鼠标灵敏度"),TEXT("Mouse sensitivity")},
{TEXT("保留设置"),TEXT("Keep settings")},
{TEXT("制式手枪"),TEXT("Service Pistol")},
{TEXT("声音设置"),TEXT("Audio")},
{TEXT("开始游戏"),TEXT("Start game")},
{TEXT("手雷补给"),TEXT("Grenade")},
{TEXT("扫描中…"),TEXT("Scanning...")},
{TEXT("操作说明"),TEXT("How to play")},
{TEXT("显示模式"),TEXT("Window mode")},
{TEXT("最终撤离"),TEXT("EXTRACTION")},
{TEXT("窗口模式"),TEXT("Windowed")},
{TEXT("终止零号"),TEXT("TERMINATE ZERO")},
{TEXT("继续游戏"),TEXT("Resume game")},
{TEXT("装甲重卫"),TEXT("Armored Sentinel")},
{TEXT("退出游戏"),TEXT("Quit game")},
{TEXT("重型机枪"),TEXT("Heavy Machine Gun")},
{TEXT("重新开始"),TEXT("Restart")},
{TEXT("隔离协议"),TEXT("QUARANTINE")},
{TEXT("主角："),TEXT("Responder: ")},
{TEXT("医疗包"),TEXT("Medkit")},
{TEXT("工程师"),TEXT("engineer")},
{TEXT("弹药箱"),TEXT("Ammo crate")},
{TEXT("林岑："),TEXT("Lin Cen: ")},
{TEXT("供电"),TEXT("power")},
{TEXT("全屏"),TEXT("Fullscreen")},
{TEXT("医疗"),TEXT("Medkit")},
{TEXT("空格"),TEXT("Space")},
{TEXT("跳跃"),TEXT("Jump")},
{TEXT("测"),TEXT("M")},
